In [2]:
import pandas as pd

In [7]:
kayak_sentiment = pd.read_csv("kayak_roberted.csv")

In [19]:
kayak_full = kayak.dropna(subset=['review'])
all_reviews = ' '.join(kayak_full['review'].astype(str))
words = all_reviews.lower().split()

word_counts = {}

for word in words:
    if word in word_counts:
        word_counts[word] += 1
    else:
        word_counts[word] = 1

word_counts_df = pd.DataFrame(list(word_counts.items()), columns=['Word', 'Count'])

sorted_word_counts = word_counts_df.sort_values(by='Count', ascending=False)

sorted_word_counts.to_csv('wordCount.csv', index=False)

In [14]:
kayak_sentiment[kayak_sentiment['rating'] == 5].sort_values(by='roberta_neg', ascending=False)

,year,rating,review,roberta_neg,roberta_neu,roberta_pos
14973,2015,5,Yet another reason to hate Hotwire and it's te...,3.382139,-0.677179,-2.669441
8695,2013,5,Airlines are scum! Lower your prices! Too many...,3.054782,-0.521517,-2.656458
739,2020,5,Can you please add a function to exclude certa...,3.032803,-0.151274,-2.992691
1702,2018,5,Orbitz is ass..... like so ass......kayak all ...,3.007013,-0.531261,-2.525704
7932,2013,5,Don't know how well it works because it locks ...,2.978859,-0.537830,-2.577935
...,...,...,...,...,...,...
5474,2015,5,KAYAK is my personal travel agency that offers...,-3.603434,1.232441,2.335690
13600,2011,5,I use Kayak almost every time when planning fo...,-3.616791,0.934781,3.009098
1389,2022,5,Booking a trip to Mexico Colombia Brazil from ...,-3.617795,1.777778,1.889772
12287,2012,5,Ive used Kayak to book my family trip to Disne...,-3.649489,1.032245,2.784148
5526,2014,5,"Booked my trip to Ireland, Seattle, and back a...",-3.708904,1.062496,2.964651

## Skyscanner 2020

In [11]:
skyscanner = pd.read_csv("../data/skyscanner_final.csv")
kayak = pd.read_csv("../data/kayak_final.csv")

In [12]:
skyscanner

,year,rating,review,roberta_neg,roberta_neu,roberta_pos
0,2023,5,This app is great! But I have a suggestion. It...,-2.366167,0.041758,2.773424
1,2021,3,"Upon updating the app, it appears that a lot o...",1.427508,0.138611,-1.749099
2,2020,1,The latest version as of 25DEC2020 is absolute...,2.564242,-0.412785,-2.259642
3,2020,1,The New View is Terrible! Primarily for esthet...,0.817050,0.057151,-0.882952
4,2021,1,"Years ago, I found great flights on this app. ...",-0.748656,-0.263892,1.354573
...,...,...,...,...,...,...
17690,2018,5,"My vacation always starts with skyscanner, esp...",-2.223770,1.319033,1.075548
17691,2016,4,Only just opened Skyscanner and I think it's j...,-2.540681,0.442104,2.425169
17692,2017,5,Already booked two of my cheapest flights from...,-3.408723,1.071380,2.481618
17693,2017,5,This app help me a lot to find tickets for air...,-3.069469,0.547620,2.813903
17694,2023,5,mr.kailash.singh.m.b.a.aacharg.harmau.ranchi.g...,-0.377170,1.391151,-0.909893